apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-app
  labels:
    app: project

spec:
  replicas: 3          
  selector:
    matchLabels:
      app: project
  template:
    metadata:
      labels:
        app: project
    spec:               
      containers:
      - name: project
        image: nginx:latest
        ports:
        - containerPort: 8000
